# Server
server.port=8080

# ===============================
# MYSQL DATABASE CONFIG (Railway FIXED)
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/gotokartDB
spring.datasource.username=gotokart
spring.datasource.password="Gotokart#2026Ec2"
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONNECTION STABILITY (IMPORTANT)
# ===============================

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# ===============================
# OPTIONAL
# ===============================

spring.jackson.serialization.fail-on-empty-beans=false
